<?php

session_start();

if(!isset($_SESSION['loggedin']) || $_SESSION['loggedin'] !==true)
{
    header("location: login.php");
}


?>
<!DOCTYPE html>
<html>
<!-- Mirrored from www.CodeWithAaryan.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 22 Jul 2022 10:57:33 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charSet="utf-8" />
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
    <script async="" src="../pagead2.googlesyndication.com/pagead/js/fa428.txt?client=ca-pub-9655830461045889"
        crossorigin="anonymous"></script>
    <title>Home | CodeWithAaryan</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="favicon.html" />
    <meta name="next-head-count" content="7" />
    <meta name="next-font-preconnect" />
    <link rel="preload" href="css/c2a8c86eebdcf29d.css" as="style" />
    <link rel="stylesheet" href="css/c2a8c86eebdcf29d.css" data-n-g="" />
    <link rel="preload" href="css/470c5e8db7cdc7e9.css" as="style" />
    <link rel="stylesheet" href="css/470c5e8db7cdc7e9.css" data-n-p="" />
    <link rel="preload" href="css/ef46db3751d8e999.css" as="style" />

    <link rel="stylesheet" href="css/ef46db3751d8e999.css" data-n-p="" /><noscript
        data-n-css=""></noscript>

</head>

<body>
    <div id="__next">
        <div class=""
            style="position:fixed;top:0;left:0;height:2px;background:transparent;z-index:99999999999;width:100%">
            <div class="" style="height:100%;background:purple;transition:all 500ms ease;width:0%">
                <div
                    style="box-shadow:0 0 10px purple, 0 0 10px purple;width:5%;opacity:1;position:absolute;height:100%;transition:all 500ms ease;transform:rotate(3deg) translate(0px, -4px);left:-10rem">
                </div>
            </div>
        </div>
     <div class="w-full z-10 sticky bg-white top-0 border-b border-grey-light shadow-md"> 
            <div class="w-full flex flex-wrap items-center lg:justify-between mt-0 py-4">
                <div
                    class="px-0 lg:pl-4 flex items-center lg:mx-4 cursor-pointer text-purple-700 text-xl font-bold mx-3">
                    <a href="index.php">CodeWithAaryan</a>
                </div>
                <div class="flex items-center md:hidden">
                    <div class="text-purple-700 text-md font-semibold">Menu</div><svg stroke="currentColor"
                        fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" class="text-purple-700 mt-1"
                        height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M840.4 300H183.6c-19.7 0-30.7 20.8-18.5 35l328.4 380.8c9.4 10.9 27.5 10.9 37 0L858.9 335c12.2-14.2 1.2-35-18.5-35z">
                        </path>
                    </svg>
                </div><a href="login.php"><button
                    class="md:hidden text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-3 py-2 text-center inline-flex items-center mx-1 absolute right-3 md:right-12">Login</button></a>
                <div class="w-full flex-grow lg:flex lg:flex-1 lg:content-center lg:justify-end lg:w-auto h-0 lg:h-auto overflow-hidden mt-2 lg:mt-0 z-20 transition-all"
                    id="nav-content">
                    <ul class="flex items-center flex-col lg:flex-row">
                        <div id="search-toggle" class="search-icon cursor-pointer px-6 hidden"><svg
                                class="fill-current pointer-events-none text-grey-darkest w-4 h-4 inline"
                                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                <path
                                    d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z">
                                </path>
                            </svg></div>
                        <li class="mx-2 my-2 text-black hover:border-b-2 hover:border-purple-700"><a
                                href="index.php">Home</a></li>
                        <li class="mx-2 my-2 text-black hover:border-b-2 hover:border-purple-700"><a
                                href="videos/index.php">Courses</a></li>
                       
                        <li class="mx-2 my-2 text-black hover:border-b-2 hover:border-purple-700"><a
                                href="contact/index.php">Contact</a></li>
                    </ul>
                     <div class="text-center my-2 px-4">
                        <a href="./logout.php"><button class="text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-3 py-2 text-center inline-flex items-center mx-1">Logout</button></a>       
                      </div>


            </div>
            
            <hr>
            
            
                <h3><?php echo "Welcome ". $_SESSION['username']?>!</h3>
           

</body>

</html>